### ISSUE TITLE
Travis times are long again

### ISSUE THREAD

**Issue by bradjc** [helena-project/tock#356]
With setting the version of rustfmt, travis is taking 10+ minutes again. Compare:

https://travis-ci.org/helena-project/tock/jobs/216617222#L179

and

https://travis-ci.org/helena-project/tock/jobs/218303884#L183

**Comment by ppannuto** [comment]
hrmm.. this almost certainly b/c Travis isn't picking up the cargo build cache with the forced version ( https://github.com/helena-project/tock/blob/master/.travis.yml#L4 )

ohh... actually, I'm guessing the problem is the `--force` flag from https://github.com/helena-project/tock/blob/master/.travis.yml#L25 -- only need that to override / change versions, which we can solve by clearing the travis build cache whenever we change rustfmt versions.  Will try that fix momentarily
