### ISSUE TITLE
sosp/sensys tutorials not working

### ISSUE THREAD

**Issue by dverhaert** [helena-project/tock#765]
In the third agenda point of both the SOSP and SenSys tutorials "Add a new capsule to the kernel", the user is required to compile and program the kernel:

$ cd doc/courses/(sosp or sensys)/exercises/board
$ make program

However doing this leads to the error "failed to resolve. Could not find `symmetric_encryption` in `capsules`". The cause is this capsule being removed, and replaced by aes_ccm.rs.

**Comment by bradjc** [comment]
Thanks for pointing this out. We knew this would happen, as keeping those tutorials up to date is tricky and not something we want to focus on. Our plan was to move them to a separate repo, and make the correct commit of Tock a dependency so there wouldn't be errors like this. That is unfortunately tricky, because as toolchain versions keep increasing and changing things, running arbitrarily old versions of Tock is difficult.

In the mean time I've made a pull request that should allow the boards in the courses folder to compile.
