### ISSUE TITLE
Thoughts on sub platforms / new platforms / out-of-tree builds?

### ISSUE THREAD

**Issue by bradjc** [helena-project/tock#92]
Any thoughts on how we should manage Tock with new drivers and new platforms? Is there a way I can specify my own `main.rs` (based on the SAM4L still) for my own platform that has a certain set of sensors and build it against the main Tock repo?

**Comment by alevy** [comment]
Yes there is, and it should start to be pretty simple to do out-of-tree so once we have #90.

### Before #90 

Create a new platform as a subdirectory of `src/platform` and basically replicate what we're doing in the `storm` folder. Unfortunately it more or less has to be in-tree because the Makefile system really cares where everything lives, and there is no way to, e.g., call `make` from within a platform subdirectory. In theory you'd need to create a new `Makefile.[platform].mk` in `apps` as well, but if you're programming the app separately the specific firestorm-based platform doesn't really matter.

## After #90 

You'll create a totally separate crate anywhere you want (e.g. different repo). It will need a `Cargo.toml` file which includes dependencies to whatever crates it needs (e.g. the `sam4l`, `main` `common`, `drivers` etc crates) probably a copy of the SAM4L's target.json and maybe of it's linker script (haven't figured that part out yet).

If you want to make your separate driver you can either do that within the same crate (e.g. if it's pretty platform specific or just for simplicity at first) or have that live in a separate crate/repo as well. For example, it would probably make sense to start separating drivers into functional crates -- as in, one for various environment sensors (isl, tmp006, accelerometer, humidity sensors etc).
